### PR TITLE
added the collaboration form part

### PR DESCRIPTION
**Pull request by ankit98040**
line 245 to 262 on index.html

line 374 to 398 on style.css

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
Screenshot from 2020-06-11 21-41-50
@ankit98040 Please change the form styling atleast make one eye appealing version take help from google and give me an update by tomorrow morning 12 PM

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
See the comment on the previous reply for the change request

**Comment by ankit98040** [comment]
Screenshot 2020-06-11 at 11 39 00 PM
having some issues with the css part.

**Comment by ayan-biswas0412** [comment]
this is not needed now anyway good work

**Pull request closed without merging**
